openapi: 3.1.0
info:
  version: 1.0.0
  title: federation et collectivite agricole
  description: digitalisation dans le domaine agricole

servers:
  - url: http://localhost:8080

paths:
  /collectivite:
    post:
      summary: creation d'une collectivite agricole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectiviteAgricole'
      responses:
        '201':
          description: Collectivite creee avec succes
        '400':
          description: parametre invalide

  /admission:
    post:
      summary: ajouter un membre dans la collectivité
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NouveauMembre'
      responses:
        '200':
          description: le nouveau membre a été ajouter dans la collectivité
        '404':
          description: votre requete n a pas ete aboutis

  /cotisation:
    post:
      summary: faire une cotisation pour la collectivité
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cotisation'
      responses:
        '200':
          description: vous avez fait une cotisation pour la collectivité
        '404':
          description: votre cotisation a été un echeque


components:
  schemas:
    membre:
      type: object
      properties:
        id:
          type: integer
        nomPrenom:
          type: string
        dateNaissance:
          type: string
          format: date-time
        adress:
          type: string
        metierExerce:
          type: string
        telephone:
          type: string
        adressEmail:
          type: string
        dateAdhesion:
          type: string
          format: date-time
        poste:
          type: string
          enum:
            - président
            - président adjoint
            - trésorier
            - secrétaire
            - membre confirmé
            - membre junior

    CollectiviteAgricole:
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        specialite:
          type: string
        dateCreation:
          type: string
          format: date-time
        membres:
          type: array
          items:
            $ref: '#/components/schemas/membre'
        ville:
          type: string
        autorisation:
          type: boolean
      example:
        id: 3
        nom: "Cooperative Rizicole d'Ambatondrazaka"
        specialite: "Culture du riz"
        dateCreation: "2015-03-10T00:00:00Z"
        membres:
          - id: 1
            nomPrenom: "Rakoto Jean"
            dateNaissance: "1980-03-15T00:00:00Z"
            adress: "Antananarivo"
            metierExerce: "Agriculteur"
            telephone: "+261341234567"
            adressEmail: "rakoto.jean@example.com"
            dateAdhesion: "2023-06-01T00:00:00Z"
            poste: "président"
        ville: "Antananarivo"
        autorisation: true

    NouveauMembre:
      type: object
      properties:
        parrainId:
          type: integer
          description: ID du membre parrain (ancienneté > 90 jours)
        nomPrenoms:
          type: string
        dateNaissance:
          type: string
          format: date
        genre:
          type: string
          enum: [ Homme, Femme, Autre ]
        adresse:
          type: string
        metierExerce:
            type: string
        telephone:
            type: string
        email:
            type: string
            format: email
        paiement:
            type: object
        properties:
            montant:
              type: number
              example: 50000
              devise:
                devise:
                  type: string
                  example: MGA
                  mode:
                    type: string
                    enum: [ MobileMoney, VirementBancaire ]
                  required:
                    - parrainId
                    - nomPrenoms
                    - dateNaissance
                    - genre
                    - adresse
                    - metierExerce
                    - telephone
                    - email
      example:
            parrainId: 12
            nomPrenoms: "Rakoto Jean"
            dateNaissance: "1985-06-15"
            genre: "Homme"
            adresse: "Antananarivo, Madagascar"
            metierExerce: "Agriculteur"
            telephone: "+261341234567"
            email: "rakoto.jean@example.com"
            paiement:
              montant: 5000
              devise: "Ar"
              mode: "MobileMoney"


    Cotisation:
      type: object
      properties:
        membreId:
          type: integer
          description: ID du membre qui verse la cotisation
        typeCotisation:
          type: string
          enum: [ Mensuelle, Annuelle, Ponctuelle ]
          description: Nature de la cotisation
        montant:
          type: number
          example: 20000
        devise:
          type: string
          example: Ar
        dateEncaissement:
          type: string
          format: date
          description: Date de l’encaissement
        modePaiement:
          type: string
          enum: [ Espece, VirementBancaire, MobileMoney ]
        traceTresorier:
          type: string
          description: Référence ou note du trésorier
      required:
        - membreId
        - typeCotisation
        - montant
        - devise
        - dateEncaissement
        - modePaiement

      example:
        membreId: 45
        typeCotisation: Mensuelle
        montant: 20000
        devise: Ar
        dateEncaissement: "2026-04-20"
        modePaiement: MobileMoney
        traceTresorier: "Reçu n°12345 - Avril"

